services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seriesdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ../series-ranking
      dockerfile: Dockerfile
    container_name: spring_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/seriesdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../series-ranking-front
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: